CC = cc
CCFLAGS = -Wall -Wextra -Werror -c
NAME = libft.a
CFILES = ft_memcpy.c ft_memset.c ft_bzero.c\
		ft_isalnum.c ft_isalpha.c ft_isascii.c\
		ft_isdigit.c ft_isprint.c ft_atoi.c\
		ft_strlen.c ft_tolower.c ft_toupper.c\
		ft_strlcpy.c ft_strncmp.c ft_strlcat.c\
		ft_memmove.c ft_memcmp.c ft_strchr.c\
		ft_strrchr.c ft_memchr.c ft_strnstr.c\
		ft_calloc.c ft_strdup.c ft_substr.c\

BFILES = ${CFILES:.c=.o}
RM = rm -f
all: ${NAME}
${NAME}: ${BFILES}
	ar rc ${NAME} ${BFILES}
${BFILES}: ${CFILES}
	${CC} ${CCFLAGS} ${CFILES}

clean:
	${RM} ${BFILES}
fclean: clean
	${RM} ${NAME}
re: fclean all
